# Generated by Django 4.2.7 on 2023-11-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scotchapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images', verbose_name='Изображение')),
                ('title', models.CharField(max_length=80, verbose_name='Название')),
                ('weight', models.CharField(max_length=15, verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(default=0, max_length=120, verbose_name='Состав')),
                ('type', models.CharField(choices=[('eat', 'Закуски'), ('soup', 'Супы'), ('pizza', 'Пицца'), ('pasta', 'Паста'), ('sandwitch', 'Сэндвичи'), ('hot', 'Горячие блюда'), ('desert', 'Десерты'), ('drinks', 'Напитки'), ('sous', 'Соусы'), ('salat', 'Салаты')], default='eat', max_length=15, verbose_name='Категория')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
