# Generated by Django 4.2.7 on 2023-11-20 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotchapp', '0002_menuitem_remove_product_category_delete_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='weight',
        ),
    ]
