# Generated by Django 4.2.7 on 2023-11-20 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scotchapp', '0004_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='menu_item',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
